# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1f416b78-cafd-4ad1-a37c-13142bfff2fd";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "autodefrag"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/4259-FED9";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/9f4f0f39-eadf-4fb0-827d-1c9a72b45f75";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "autodefrag"
      "space_cache=v2"
    ];
  };

  fileSystems."/opt/games" = {
    device = "/dev/disk/by-uuid/9f4f0f39-eadf-4fb0-827d-1c9a72b45f75";
    fsType = "btrfs";
    options = [
      "subvol=@games"
      "compress=zstd"
      "autodefrag"
      "space_cache=v2"
    ];
  };

  fileSystems."/srv/backups" = {
    device = "/dev/disk/by-uuid/9f4f0f39-eadf-4fb0-827d-1c9a72b45f75";
    fsType = "btrfs";
    options = [
      "subvol=@backups"
      "compress=zstd"
      "autodefrag"
      "space_cache=v2"
    ];
  };

  fileSystems."/srv/vms" = {
    device = "/dev/disk/by-uuid/9f4f0f39-eadf-4fb0-827d-1c9a72b45f75";
    fsType = "btrfs";
    options = [
      "subvol=@vms"
      "compress=zstd"
      "autodefrag"
      "space_cache=v2"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e6368fbe-43b1-4f57-8bfc-e0fda7849036"; }
  ];

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 35;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
